# Setup
title:               HosseinToussi
tagline:             'A simple blog'
url:                 http://hosseintoussi.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Hossein Toussi
  url:               bitbucket.org/hosseintoussi
  email:             saeed.toussi@yahoo.com
